---
title: "Peel-1 negative selection"
output: html_document
---

```{r setup, include=FALSE}
##Load libraries

library(tidyverse)
library(scales)
library(broom)

```


```{r}

##Making a plot of the proportion of plates showing signs of starvation. 

##Read in starvation data 

setwd("/Users/troymcdiarmid/Documents/Peel_materials/peel_selection_data")

starve_data <- read_csv("/Users/troymcdiarmid/Documents/Peel_materials/peel_plate_starve.csv", col_names = TRUE)

##PLot of data for F10E9.2

starve_data_F10 <- starve_data %>% 
  filter(Gene == "F10E9.2")

ggplot(starve_data_F10, aes(fill=treatment, y=Proportion_starved, x=Gene_injector)) + geom_bar(position = position_dodge(width = 0.8), stat="identity", width = 0.5, show.legend = FALSE) +
theme_classic() +
  labs(y = "Plates with starvation (%)", x = "") +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,100)) +
  coord_cartesian(clip = "off") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.text= element_text(family="Arial Bold")) +
  theme(axis.line = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(size = 0)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black")) +
  theme(axis.text.x = element_text(size = 0)) +
  theme(axis.text.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 0)) +
  scale_fill_manual(values = c("black", "dodgerblue2")) +
ggsave("F10_Peel_starve.jpeg", width = 1.5, height = 2.2, path = "/Users/troymcdiarmid/Desktop/")

##Plot of the data for F53B6.7 

starve_data_F53 <- starve_data %>% 
  filter(Gene == "F53B6.7")

ggplot(starve_data_F53, aes(fill=treatment, y=Proportion_starved, x=Gene_injector)) + geom_bar(position = position_dodge(width = 0.8), stat="identity", width = 0.5, show.legend = FALSE) +
theme_classic() +
  labs(y = "Plates with starvation (%)", x = "") +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,100)) +
  coord_cartesian(clip = "off") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.text= element_text(family="Arial Bold")) +
  theme(axis.line = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(size = 0)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black")) +
  theme(axis.text.x = element_text(size = 0)) +
  theme(axis.text.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 0)) +
  scale_fill_manual(values = c("black", "dodgerblue2")) +
ggsave("F53_Peel_starve.jpeg", width = 1.5, height = 2.2, path = "/Users/troymcdiarmid/Desktop/")

```

```{r}
##Making a plot of the proportion of plates that were enriched for integrants in each condition. 

##Loading in integrant enrichment data

setwd("/Users/troymcdiarmid/Documents/Peel_materials/peel_selection_data")

enrich_data <- read_csv("/Users/troymcdiarmid/Documents/Peel_materials/Peel_enriched_plate_counts.csv", col_names = TRUE)

ggplot(enrich_data, aes(fill=Treatment, y=Proportion_enriched_plates, x=Injector)) + geom_bar(position = position_dodge(width = 0.7), stat="identity", width = 0.5, show.legend = FALSE) +
theme_classic() +
  labs(y = "Integrant enriched plates (%)", x = "") +
  scale_y_continuous(position = "right", expand = c(0,0),
                     limits = c(0,50)) +
  coord_cartesian(clip = "off") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.text= element_text(family="Arial Bold")) +
  theme(axis.line = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(size = 0)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black")) +
  theme(axis.text.x = element_text(size = 0)) +
  theme(axis.text.y.right = element_text(family="Arial", colour = "black", size = 8, angle = 90, hjust = 0.5)) +
  theme(axis.title.y.right = element_text(family="Arial", colour = "black", size = 8, angle = 90)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 0)) +
  scale_fill_manual(values = c("black", "dodgerblue2")) +
ggsave("enrich.jpeg", width = 1.47, height = 4.37, path = "/Users/troymcdiarmid/Desktop/")

```

```{r}
##Making a plot of the proportion of plates where integrants were found

setwd("/Users/troymcdiarmid/Documents/Peel_materials/peel_selection_data")

total_integrant_data <- read_csv("/Users/troymcdiarmid/Documents/Peel_materials/peel_screen_times.csv", col_names = TRUE)

##Create "Injector_gene" compound variable. 

total_integrant_data <- total_integrant_data %>% 
  unite(Injector_gene, Injector, Gene)

##Calculate the proportion of plates where integrants were found

total_integrant_data_day1 <- total_integrant_data %>% 
  filter(!Screening_day == 2)

integrant_proportion_data <- total_integrant_data_day1 %>% 
  group_by(Injector_gene, Treatment) %>% 
  summarise(Integrant_proportion = (mean(Integrant_found)*100))

##Order the factors for plotting

integrant_proportion_data$Injector_gene <- factor(integrant_proportion_data$Injector_gene,
    levels = c('T_F10E9.2', 'V_F10E9.2', 'T_F53B6.7', 'V_F53B6.7'), ordered = TRUE)

##Creating a plot to compare the proportion of plates bearing integrants

##Plot of the data for F53

integrant_proportion_F53 <- integrant_proportion_data %>% 
  filter(Injector_gene %in% c("T_F53B6.7", "V_F53B6.7"))

ggplot(integrant_proportion_F53, aes(fill=Treatment, y=Integrant_proportion, x=Injector_gene)) + geom_bar(position = position_dodge(width = 0.8), stat="identity", width = 0.5, show.legend = FALSE) +
theme_classic() +
  labs(y = "Plates with integrants (%)", x = "") +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,100)) +
  coord_cartesian(clip = "off") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.text= element_text(family="Arial Bold")) +
  theme(axis.line = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(size = 0)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black")) +
  theme(axis.text.x = element_text(size = 0)) +
  theme(axis.text.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 0)) +
  scale_fill_manual(values = c("black", "dodgerblue2")) +
ggsave("F53_integrant_proportion.jpeg", width = 1.5, height = 2.2, path = "/Users/troymcdiarmid/Desktop/")

##Plot of the data for F10

integrant_proportion_F53 <- integrant_proportion_data %>% 
  filter(Injector_gene %in% c("T_F10E9.2", "V_F10E9.2"))

ggplot(integrant_proportion_F53, aes(fill=Treatment, y=Integrant_proportion, x=Injector_gene)) + geom_bar(position = position_dodge(width = 0.8), stat="identity", width = 0.5, show.legend = FALSE) +
theme_classic() +
  labs(y = "Plates with integrants (%)", x = "") +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,100)) +
  coord_cartesian(clip = "off") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.text= element_text(family="Arial Bold")) +
  theme(axis.line = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(size = 0)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black")) +
  theme(axis.text.x = element_text(size = 0)) +
  theme(axis.text.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 0)) +
  scale_fill_manual(values = c("black", "dodgerblue2")) +
ggsave("F10_integrant_proportion.jpeg", width = 1.5, height = 2.2, path = "/Users/troymcdiarmid/Desktop/")

```

```{r}
##Making a plot of the effect of multiple heatshock rounds on days 5,7,9 on plate starvation 10 days post-injection

setwd("/Users/troymcdiarmid/Documents/Peel_materials/peel_selection_data")

starve_data_pbs_k04_10_579 <- read_csv("/Users/troymcdiarmid/Documents/Peel_materials/peel_selection_data/peel_plate_starve_pbs_K04_multiday.csv", col_names = TRUE)

## Plot for pbs-1

starve_data_pbs_10_579 <- starve_data_pbs_k04_10_579 %>% 
  filter(Gene %in% c("pbs-1"))

ggplot(starve_data_pbs_10_579, aes(fill=Treatment, y=Proportion_starved, x=Gene_day)) + geom_bar(position = position_dodge(width = 0.7), stat="identity", width = 0.5, show.legend = FALSE) +
theme_classic() +
  labs(y = "Plates with starvation (%)", x = "") +
  scale_y_continuous(position = "right", expand = c(0,0),
                     limits = c(0,75), breaks = c(0,25,50,75)) +
  coord_cartesian(clip = "off") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.text= element_text(family="Arial Bold")) +
  theme(axis.line = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(size = 0)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black")) +
  theme(axis.text.x = element_text(size = 0)) +
  theme(axis.text.y.right = element_text(family="Arial", colour = "black", size = 8, angle = 90, hjust = 0.5)) +
  theme(axis.title.y.right = element_text(family="Arial", colour = "black", size = 8, angle = 90)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 0)) +
  scale_fill_manual(values = c("black", "dodgerblue2")) +
ggsave("plate_starve_pbs_multiday.jpeg", width = 1.5, height = 2.8, path = "/Users/troymcdiarmid/Desktop/")

## Plot for K04F10.3

starve_data_K04_10_579 <- starve_data_pbs_k04_10_579 %>% 
  filter(Gene %in% c("K04F10.3"))

ggplot(starve_data_K04_10_579, aes(fill=Treatment, y=Proportion_starved, x=Gene_day)) + geom_bar(position = position_dodge(width = 0.7), stat="identity", width = 0.5, show.legend = FALSE) +
theme_classic() +
  labs(y = "Plates with starvation (%)", x = "") +
  scale_y_continuous(position = "right", expand = c(0,0),
                     limits = c(0,75), breaks = c(0,25,50,75)) +
  coord_cartesian(clip = "off") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.text= element_text(family="Arial Bold")) +
  theme(axis.line = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(size = 0)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black")) +
  theme(axis.text.x = element_text(size = 0)) +
  theme(axis.text.y.right = element_text(family="Arial", colour = "black", size = 8, angle = 90, hjust = 0.5)) +
  theme(axis.title.y.right = element_text(family="Arial", colour = "black", size = 8, angle = 90)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 0)) +
  scale_fill_manual(values = c("black", "dodgerblue2")) +
ggsave("plate_starve_K04_multiday.jpeg", width = 1.5, height = 2.8, path = "/Users/troymcdiarmid/Desktop/")

```


```{r}

#This section covers the Multi-Worm Tracker analysis of the K04F10.3 and pbs-1 deletion mutants generated via peel-1 DMS selection.

##Bash loop to output reversals and basic morphology from tracker plates (to be run in terminal)

for folder in $( ls ); do java -jar /Users/troymcdiarmid/Desktop/Chore.jar --segment --shadowless --pixelsize 0.027 --minimum-move-body 2 --minimum-time 20 --output width,length,morphwidth,curve,area,midline,pathlen,bias,dir,angular,aspect,kink,crab,speed --plugin Reoutline::despike --plugin Respine --plugin MeasureReversal::tap::dt=1::collect=0.5 $folder; done

##Bash argument to grep all .dat files into a summary of morphology (to be run in terminal)

grep -H '[.]*' $(find . -name '*.dat') > data.smorph

cd ../..

```


```{r}
##The following code creates a dataframe with all morphology and baseline locomotion measures throughout the tracking session.

##Comand to read .smorph file in 

setwd("/Users/troymcdiarmid/Desktop/laptop_transfer/peel1_dels_0306_2020/data")

rawsmorph <- read_table2("data.smorph", col_names = c("plate_id", "width", "length", "morphwidth", "curve", "area", "midline", "pathlen", "bias", "dir", "angular", "aspect", "kink", "crab", "speed"))

cleanrawsmorph <- rawsmorph %>% 
  separate(plate_id, into = c("garbage", "plate_id", "genotype"), sep ="/") %>%
  separate(genotype, into = c("genotype", "time"), sep = ":") %>% separate(genotype, into = c("genotype", "synch_conditions", "growth_conditions"), sep = "_") 

#Recoding to combine data from standard egg lay and bleach synched K04F10.3 animals into one group as they showed similar results. 

cleanrawsmorph$genotype <- recode(cleanrawsmorph$genotype, `K04F10B` = "K04F10S")

####Make time numeric and round time

cleanrawsmorph <- cleanrawsmorph %>% mutate(time = as.numeric(time)) %>% 
  mutate(time = round(time, digits = 0)) 

##Ordering the genotype factor for plotting
    
cleanrawsmorph$genotype <- factor(cleanrawsmorph$genotype,
    levels = c("PD1074", "K04F10S", "pbs1"), ordered = TRUE)

##Filtering to exclude first 10s when the tracker has yet to calculate conistent measurements for certain metrics.

cleanrawsmorph <- cleanrawsmorph %>% 
  filter(between(cleanrawsmorph$time, 10, 1199))

##Code to remove all 0 measurement entries and focus on the baseline period (300-599 seconds) which occurs after the worms have acclimated to the tracker but prior to the delivery of mechanosensory stimuli 

cleanrawsmorph_baseline <- cleanrawsmorph %>% 
  filter(between(cleanrawsmorph$time, 300, 599))

```


```{r}
##Code to calculate mean of morphology metrics

mean_cleanrawsmorph <- cleanrawsmorph_baseline %>% 
  dplyr::select(genotype, plate_id, width:speed) 

mean_cleanrawsmorph <- mean_cleanrawsmorph %>%  
  group_by(genotype, plate_id) %>%
  summarize_all(mean) 

```


```{r}

##Making plots of the mean length, width, and kink each genotype group. 

##Plot of length

ggplot(mean_cleanrawsmorph, aes(genotype, length, fill = genotype)) +
  geom_violin(position = position_dodge(width = 0.65), trim = FALSE, size = 0.4) +
  geom_point(position = position_jitterdodge(jitter.width = 0, jitter.height = 0.0,
  dodge.width = 0.65, seed = 3), size = 0.3) +
  scale_fill_manual(values = c("white", "dodgerblue2", "gray39")) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,1.25), breaks = c(0,.25,.50,0.75,1.00,1.25)) +
  theme_classic() +
  labs(y = "Length (mm)", x = "") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.position = "none") +
  theme(axis.line = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black")) +
  theme(axis.text.x = element_text(size = 0)) +
  theme(axis.text.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 0)) +
ggsave("length.jpeg", width = 1.7, height = 2.3, path = "/Users/troymcdiarmid/Desktop/")

##Fit a linear model and estimate signficance of group differences with adjusted p-values. 

fit <- summary(lm(length~genotype, mean_cleanrawsmorph))

tidy_fit <- tidy(fit) %>% 
  filter(term %in% c("genotype.L", "genotype.Q")) 

tidy_fit$term <- recode(tidy_fit$term, `genotype.Q` = "K04F10S", `genotype.L` = "pbs1") 

qvals <- p.adjust(tidy_fit$p.value, "BH")

tidy_fit$q.vals <- qvals

write_csv(tidy_fit, "/Users/troymcdiarmid/Documents/Analysis_scripts/peel-1/stats/length_stats.csv")

##Plot of Width

ggplot(mean_cleanrawsmorph, aes(genotype, width, fill = genotype)) +
  geom_violin(position = position_dodge(width = 0.65), trim = FALSE, size = 0.4) +
  geom_point(position = position_jitterdodge(jitter.width = 0, jitter.height = 0.0,
  dodge.width = 0.65, seed = 3), size = 0.3) +
  scale_fill_manual(values = c("white", "dodgerblue2", "gray39")) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,0.5), breaks = c(0,.25,.50)) +
  theme_classic() +
  labs(y = "Width (mm)", x = "") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.position = "none") +
  theme(axis.line = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black")) +
  theme(axis.text.x = element_text(size = 0)) +
  theme(axis.text.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 0)) +
ggsave("width.jpeg", width = 1.7, height = 2.3, path = "/Users/troymcdiarmid/Desktop/")

##Fit a linear model and estimate signficance of group differences with adjusted p-values. 

fit <- summary(lm(width~genotype, mean_cleanrawsmorph))

tidy_fit <- tidy(fit) %>% 
  filter(term %in% c("genotype.Q", "genotype.L")) 

tidy_fit$term <- recode(tidy_fit$term, `genotype.Q` = "K04F10S", `genotype.L` = "pbs1") 

qvals <- p.adjust(tidy_fit$p.value, "BH")

tidy_fit$q.vals <- qvals

write_csv(tidy_fit, "/Users/troymcdiarmid/Documents/Analysis_scripts/peel-1/stats/width_stats.csv")

##Plot of Curve

ggplot(mean_cleanrawsmorph, aes(genotype, kink, fill = genotype)) +
  geom_violin(position = position_dodge(width = 0.65), trim = FALSE, size = 0.4) +
  geom_point(position = position_jitterdodge(jitter.width = 0, jitter.height = 0.0,
  dodge.width = 0.65, seed = 3), size = 0.3) +
  scale_fill_manual(values = c("white", "dodgerblue2", "gray39")) +
    scale_y_continuous(expand = c(0,0),
                     limits = c(0, 100), breaks = c(0,25,50,75,100)) +
  theme_classic() +
  labs(y = "Kink (radians)", x = "") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.position = "none") +
  theme(axis.line = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black")) +
  theme(axis.text.x = element_text(size = 0)) +
  theme(axis.text.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 0)) +
ggsave("kink.jpeg", width = 1.7, height = 2.3, path = "/Users/troymcdiarmid/Desktop/")

##Fit a linear model and estimate signficance of group differences with adjusted p-values. 

fit <- summary(lm(kink~genotype, mean_cleanrawsmorph))

tidy_fit <- tidy(fit) %>% 
  filter(term %in% c("genotype.Q", "genotype.L")) 

tidy_fit$term <- recode(tidy_fit$term, `genotype.Q` = "K04F10S", `genotype.L` = "pbs1") 

qvals <- p.adjust(tidy_fit$p.value, "BH")

tidy_fit$q.vals <- qvals

write_csv(tidy_fit, "/Users/troymcdiarmid/Documents/Analysis_scripts/peel-1/stats/kink_stats.csv")

```


```{r}
##Code to plot the mean absolute movement speed of each genotype throughout the tracking session

mean_cleanrawsmorph_whole_session <- cleanrawsmorph %>% 
  select(genotype, time, width:speed) 

mean_cleanrawsmorph_whole_session <- mean_cleanrawsmorph_whole_session %>%  
  group_by(genotype, time) %>%
  summarize_all(mean) 

ggplot(mean_cleanrawsmorph_whole_session, aes(time, speed, colour = genotype)) + 
geom_line(size = 0.4) +
  scale_colour_manual(values = c("black", "dodgerblue2", "gray39")) +
    scale_y_continuous(expand = c(0,0),
                     limits = c(0, 0.3), breaks = c(0,0.1,0.2,0.3)) +
  theme_classic() +
  labs(y = "Speed (mm/s)", x = "") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.position = "none") +
  theme(axis.line.y = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(colour = 'black', size = 0)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black")) +
  theme(axis.text.x = element_text(size = 0)) +
  theme(axis.text.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 0)) +
ggsave("Speed_trace.jpeg", width = 5.2, height = 2.3, path = "/Users/troymcdiarmid/Desktop/")

```


```{r}
#Plot of absolute movement speed post haituation training (from 905-1189 seconds) after the tab reversal response and before the spontaneous recovery stimulus

#Filtering for just the time after mechanosensory stimulation.

cleanrawsmorph_posthab <- cleanrawsmorph %>% 
  filter(between(cleanrawsmorph$time, 905, 1189))

##Code to calculate mean of metrics 

mean_cleanrawsmorph_posthab <- cleanrawsmorph_posthab %>% 
  select(genotype, plate_id, width:speed) 

mean_cleanrawsmorph_posthab <- mean_cleanrawsmorph_posthab %>%  
  group_by(genotype, plate_id) %>%
  summarize_all(mean) 

##Plot of absolute movement speed throughout the tracking session

ggplot(mean_cleanrawsmorph_posthab, aes(genotype, speed, fill = genotype)) +
  geom_violin(position = position_dodge(width = 0.65), trim = FALSE, size = 0.4) +
  geom_point(position = position_jitterdodge(jitter.width = 0, jitter.height = 0,
  dodge.width = 0.65, seed = 3), size = 0.3) +
  scale_fill_manual(values = c("white", "dodgerblue2", "gray39")) +
    scale_y_continuous(expand = c(0,0),
                     limits = c(0, 0.2), breaks = c(0,0.1,0.2)) +
  theme_classic() +
  labs(y = "Speed (mm/s)", x = "") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.position = "none") +
  theme(axis.line = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black")) +
  theme(axis.text.x = element_text(size = 0)) +
  theme(axis.text.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 0)) +
ggsave("speed.jpeg", width = 1.7, height = 2.3, path = "/Users/troymcdiarmid/Desktop/")


##Fit a linear model and estimate signficance of group differences with adjusted p-values. 

fit <- summary(lm(speed~genotype, mean_cleanrawsmorph_posthab))

tidy_fit <- tidy(fit) %>% 
  filter(term %in% c("genotype.Q", "genotype.L")) 

tidy_fit$term <- recode(tidy_fit$term, `genotype.Q` = "K04F10S", `genotype.L` = "pbs1") 

qvals <- p.adjust(tidy_fit$p.value, "BH")

tidy_fit$q.vals <- qvals

write_csv(tidy_fit, "/Users/troymcdiarmid/Documents/Analysis_scripts/peel-1/stats/speed_stats.csv")

```


```{r}
#The following code chunks import and analyze tap reversal response habituation learning behavior from MWT output files. 

##Bash loop to call choreography to output reversals from each tracker plate data file generated by the tracker

for folder in $( ls ); do java -jar /Users/troymcdiarmid/Desktop/Chore.jar --segment --shadowless --pixelsize 0.027 --minimum-move-body 2 --minimum-time 20 --output speed,midline,morphwidth --plugin Reoutline::despike --plugin Respine --plugin MeasureReversal::tap::dt=1::collect=0.5  $folder; done

##Bash argument to grep all .trv choreography output files into a summary of reversals

grep -H '[.]*' $(find . -name '*.rev') > data.srev
cd ../..

```


```{r}
##Read in summary of reversal data file (data.srev) 

setwd("/Users/troymcdiarmid/Desktop/laptop_transfer/peel1_dels_0306_2020/data")
cleanrawsrev <- read_table2("data.srev", col_names = c("plate_id", "already_rev", "not_rev", "rev", "rev_dist", "dist_sd", "dist_sem", "dist_0_quart", "dist_1st_quart", "dist_2nd_quart", "dist_3rd_quart", "dsit_100th_percentile", "rev_dur", "dur_sd", "dur_sem", "dur_0_quart", "dur_1st_quart", "dur_2nd_quart", "dur_3rd_quart", "dur_100th_percentile"))
cleanrawsrev <- cleanrawsrev %>% 
  separate(plate_id, into = c("garbage", "plate_id", "genotype"), sep ="/") %>%
  separate(genotype, into = c("genotype", "time"), sep = ":") %>% 
  separate(genotype, into = c("genotype", "synch_conditions", "growth_conditions"), sep = "_") 

####Make time numeric and round time

cleanrawsrev <- cleanrawsrev %>% mutate(time = as.numeric(time)) %>% 
  mutate(time = round(time, digits = 0)) 

#Recoding to combine data from standard egg lay and bleach synched K04F10.3 animals into one group as they showed similar results. 

cleanrawsrev$genotype <- recode(cleanrawsrev$genotype, `K04F10B` = "K04F10S")

##Ordering the genotype factor for plotting
    
cleanrawsrev$genotype <- factor(cleanrawsrev$genotype,
    levels = c("PD1074", "K04F10S", "pbs1"), ordered = TRUE)

##Calculate reversal probability

cleanrawsrev <- cleanrawsrev %>% 
  mutate(rev_prob = rev / (not_rev + rev)) 

##optional code to remove any bad observtions

cleanrawsrev <- cleanrawsrev %>% 
  filter(!(rev_dist == "0")) 
cleanrawsrev <- cleanrawsrev %>% 
  filter(!(time == "659")) 

##Calculate reversal speed 

cleanrawsrev <- cleanrawsrev %>%
  mutate(rev_speed = rev_dist / rev_dur) 

##Mean rev data

mean_cleanrawsrev <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarize_all(mean) 

##Add stim number NOTE: this must be changed to fit your experiment parameters 

mean_cleanrawsrev$stimulus_num <- rep(1:31, times = 3) 

##SD calcs

prob_SD <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarise(prob_sd = sd(rev_prob))
dur_SD <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarise(dur_sd = sd(rev_dur))
speed_SD <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarise(speed_sd = sd(rev_speed))
dist_SD <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarise(dist_sd = sd(rev_dist))

##SEM calcs

prob_SEM <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarise(prob_sem = sd(rev_prob)/sqrt(length(rev_prob)))
dur_SEM <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarise(dur_sem = sd(rev_dur)/sqrt(length(rev_dur)))
dist_SEM <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarise(dist_sem = sd(rev_dist)/sqrt(length(rev_dist)))
speed_SEM <- cleanrawsrev %>% 
  group_by(genotype, time) %>% 
  summarise(speed_sem = sd(rev_speed)/sqrt(length(rev_speed)))

```


```{r}
##Plots of mean reversal probability for PD1074 wild-type controls vs pbs-1 heterozygotes.

mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("PD1074", "K04F10S", "pbs1"))
prob_SEM_filt <- prob_SEM %>% 
  filter(genotype %in% c("PD1074", "K04F10S", "pbs1"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_prob, colour = genotype)) +
  theme_classic() + 
  geom_line(size = 0.4) + 
  geom_errorbar(aes(ymin=rev_prob-prob_SEM_filt$prob_sem, ymax=rev_prob+prob_SEM_filt$prob_sem), width = 0, size = 0.4) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,1.00), breaks = c(0,0.5,1.0)) +
  scale_x_continuous(expand = c(0,0),
                     limits = c(0,32), breaks = c(0,31)) +
  geom_point(size = 0.8) +
  scale_color_manual(values=c("black", "dodgerblue2", "gray39")) +
  labs(title = "", x = "Stimulus number", y = "Reversal probability") +
  theme(axis.line = element_line(colour = 'black', size = 0.4)) +
  theme(axis.ticks = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length= unit(.03, "in")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(legend.position="none") +
  ggsave("PD1074_vs_pbs1_vs_K04F103_prob.jpeg", width = 2.3, height = 2.2, path = "/Users/troymcdiarmid/Desktop/")

#Plot of duration habituation
  
mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("PD1074", "K04F10S", "pbs1"))
dur_SEM_filt <- dur_SEM %>% 
  filter(genotype %in% c("PD1074", "K04F10S", "pbs1"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_dur, colour = genotype)) +
  theme_classic() + 
  geom_line(size = 0.4) + 
  geom_errorbar(aes(ymin=rev_dur-dur_SEM_filt$dur_sem, ymax=rev_dur+dur_SEM_filt$dur_sem), width = 0, size = 0.4) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,3.00), breaks = c(0,1.0,2.0,3.0)) +
  scale_x_continuous(expand = c(0,0),
                     limits = c(0,32), breaks = c(0,31)) +
  geom_point(size = 0.8) +
  scale_color_manual(values=c("black", "dodgerblue2", "gray39")) +
  labs(title = "", x = "Stimulus number", y = "Reversal duration") +
  theme(axis.line = element_line(colour = 'black', size = 0.4)) +
  theme(axis.ticks = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length= unit(.03, "in")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(legend.position="none") +
  ggsave("PD1074_vs_pbs1_vs_K04F103_dur.jpeg", width = 2.3, height = 2.2, path = "/Users/troymcdiarmid/Desktop/")

##Plot of speed habituation

mean_cleanrawsrev_filt <- mean_cleanrawsrev %>% 
  filter(genotype %in% c("PD1074", "K04F10S", "pbs1"))
speed_SEM_filt <- speed_SEM %>% 
  filter(genotype %in% c("PD1074", "K04F10S", "pbs1"))
ggplot(mean_cleanrawsrev_filt, aes(stimulus_num, rev_speed, colour = genotype)) +
  theme_classic() + 
  geom_line(size = 0.4) + 
  geom_errorbar(aes(ymin=rev_speed-speed_SEM_filt$speed_sem, ymax=rev_speed+speed_SEM_filt$speed_sem), width = 0, size = 0.4) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,0.5), breaks = c(0,0.1,0.2,0.3,0.4,0.5)) +
  scale_x_continuous(expand = c(0,0),
                     limits = c(0,32), breaks = c(0,31)) +
  geom_point(size = 0.8) +
  scale_color_manual(values=c("black", "dodgerblue2", "gray39")) +
  labs(title = "", x = "Stimulus number", y = "Reversal speed") +
  theme(axis.line = element_line(colour = 'black', size = 0.4)) +
  theme(axis.ticks = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length= unit(.03, "in")) +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(legend.position="none") +
  ggsave("PD1074_vs_pbs1_vs_K04F103_speed.jpeg", width = 2.3, height = 2.2, path = "/Users/troymcdiarmid/Desktop/")

##Calculate the final probability of responding after habituation training for statistical comparisons. 

Final_rev_prob <- cleanrawsrev %>%
  group_by(genotype, plate_id) %>%
  filter(time %in% c(870:890)) %>% 
  summarize(final_rev_prob = mean(rev_prob))

##Fit a linear model and estimate signficance of group differences with adjusted p-values. 

fit <- summary(lm(final_rev_prob~genotype, Final_rev_prob))

tidy_fit <- tidy(fit) %>% 
  filter(term %in% c("genotype.Q", "genotype.L")) 

tidy_fit$term <- recode(tidy_fit$term, `genotype.Q` = "K04F10S", `genotype.L` = "pbs1") 

qvals <- p.adjust(tidy_fit$p.value, "BH")

tidy_fit$q.vals <- qvals

write_csv(tidy_fit, "/Users/troymcdiarmid/Documents/Analysis_scripts/peel-1/stats/final_rev_prob_stats.csv")

##Calculate the final duration of responses after habituation training for statistical comparisons. 

Final_rev_dur <- cleanrawsrev %>%
  group_by(genotype, plate_id) %>%
  filter(time %in% c(870:890)) %>% 
  summarize(final_rev_dur = mean(rev_dur))

##Fit a linear model and estimate signficance of group differences with adjusted p-values. 

fit <- summary(lm(final_rev_dur~genotype, Final_rev_dur))

tidy_fit <- tidy(fit) %>% 
  filter(term %in% c("genotype.Q", "genotype.L")) 

tidy_fit$term <- recode(tidy_fit$term, `genotype.Q` = "K04F10S", `genotype.L` = "pbs1") 

qvals <- p.adjust(tidy_fit$p.value, "BH")

tidy_fit$q.vals <- qvals

write_csv(tidy_fit, "/Users/troymcdiarmid/Documents/Analysis_scripts/peel-1/stats/final_rev_dur_stats.csv")

Final_rev_speed <- cleanrawsrev %>%
  group_by(genotype, plate_id) %>%
  filter(time %in% c(870:890)) %>% 
  summarize(final_rev_speed = mean(rev_speed))

##Fit a linear model and estimate signficance of group differences with adjusted p-values. 

fit <- summary(lm(final_rev_speed~genotype, Final_rev_speed))

tidy_fit <- tidy(fit) %>% 
  filter(term %in% c("genotype.Q", "genotype.L")) 

tidy_fit$term <- recode(tidy_fit$term, `genotype.Q` = "K04F10S", `genotype.L` = "pbs1") 

qvals <- p.adjust(tidy_fit$p.value, "BH")

tidy_fit$q.vals <- qvals

write_csv(tidy_fit, "/Users/troymcdiarmid/Documents/Analysis_scripts/peel-1/stats/final_rev_speed_stats.csv")

```


