---
title: "Peel-1 negative selection"
output: html_document
---

```{r setup, include=FALSE}
##Load libraries

library(tidyverse)
library(scales)

```


```{r}

##Making a plot of the proportion of plates showing signs of starvation. 

##Read in starvation data 

setwd("/Users/troymcdiarmid/Documents/Peel_materials/")

starve_data <- read_csv("/Users/troymcdiarmid/Documents/Peel_materials/peel_plate_starve.csv", col_names = TRUE)

##PLot of data for F10E9.2

starve_data_F10 <- starve_data %>% 
  filter(Gene == "F10E9.2")

ggplot(starve_data_F10, aes(fill=treatment, y=Proportion_starved, x=Gene_injector)) + geom_bar(position = position_dodge(width = 0.8), stat="identity", width = 0.5, show.legend = FALSE) +
theme_classic() +
  labs(y = "Plates with starvation (%)", x = "") +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,100)) +
  coord_cartesian(clip = "off") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.text= element_text(family="Arial Bold")) +
  theme(axis.line = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(size = 0)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black")) +
  theme(axis.text.x = element_text(size = 0)) +
  theme(axis.text.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 0)) +
  scale_fill_manual(values = c("black", "dodgerblue2")) +
ggsave("F10_Peel_starve.jpeg", width = 1.5, height = 2.2, path = "/Users/troymcdiarmid/Desktop/")

##Plot of the data for F53

starve_data_F53 <- starve_data %>% 
  filter(Gene == "F53B6.7")

ggplot(starve_data_F53, aes(fill=treatment, y=Proportion_starved, x=Gene_injector)) + geom_bar(position = position_dodge(width = 0.8), stat="identity", width = 0.5, show.legend = FALSE) +
theme_classic() +
  labs(y = "Plates with starvation (%)", x = "") +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,100)) +
  coord_cartesian(clip = "off") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.text= element_text(family="Arial Bold")) +
  theme(axis.line = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(size = 0)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black")) +
  theme(axis.text.x = element_text(size = 0)) +
  theme(axis.text.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 0)) +
  scale_fill_manual(values = c("black", "dodgerblue2")) +
ggsave("F53_Peel_starve.jpeg", width = 1.5, height = 2.2, path = "/Users/troymcdiarmid/Desktop/")

```

```{r}
##Making a plot of the proportion of plates that were enriched for integrants in each condition. 

##Loading in integrant enrichment data

setwd("/Users/troymcdiarmid/Documents/Peel_materials/")

enrich_data <- read_csv("/Users/troymcdiarmid/Documents/Peel_materials/Peel_enriched_plate_counts.csv", col_names = TRUE)

ggplot(enrich_data, aes(fill=Treatment, y=Proportion_enriched_plates, x=Injector)) + geom_bar(position = position_dodge(width = 0.7), stat="identity", width = 0.5, show.legend = FALSE) +
theme_classic() +
  labs(y = "Integrant enriched plates (%)", x = "") +
  scale_y_continuous(position = "right", expand = c(0,0),
                     limits = c(0,50)) +
  coord_cartesian(clip = "off") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.text= element_text(family="Arial Bold")) +
  theme(axis.line = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(size = 0)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black")) +
  theme(axis.text.x = element_text(size = 0)) +
  theme(axis.text.y.right = element_text(family="Arial", colour = "black", size = 8, angle = 90, hjust = 0.5)) +
  theme(axis.title.y.right = element_text(family="Arial", colour = "black", size = 8, angle = 90)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 0)) +
  scale_fill_manual(values = c("black", "dodgerblue2")) +
ggsave("enrich.jpeg", width = 1.5, height = 2.8, path = "/Users/troymcdiarmid/Desktop/")

```


```{r}
##Making a plot of the screening time taken to find integrants under each condition. 

##Loading in plate screening time data

setwd("/Users/troymcdiarmid/Documents/Peel_materials/")

screen_time_data <- read_csv("/Users/troymcdiarmid/Documents/Peel_materials/Peel_screen_times.csv", col_names = TRUE)

##Create "Injector_gene" compound variable. 

screen_time_data <- screen_time_data %>% 
  unite(Injector_gene, Injector, Gene)

##Remove plates that took 5 mins to screen as no integrant was found in the 5 minute screening period. 

screen_time_integrant_data <- screen_time_data %>% 
  filter(!Screening_time == 300)

##Make a violin/boxplot of screening times

screen_time_integrant_data$Injector_gene <- factor(screen_time_integrant_data$Injector_gene,
    levels = c('T_F10E9.2', 'V_F10E9.2', 'T_F53B6.7', 'V_F53B6.7'), ordered = TRUE)

ggplot(screen_time_integrant_data, aes(x = Injector_gene, y = Screening_time, fill = Treatment)) + 
  geom_violin(position = position_dodge(width = 0.65), trim = FALSE, size = 0.4) +
  geom_point(position = position_jitterdodge(jitter.width = 0, jitter.height = 0.05,
  dodge.width = 0.65, seed = 3), size = 0.3) +
  scale_fill_manual(values = c("white", "dodgerblue2")) +
   scale_y_log10("Screening time (S)",
        breaks = trans_breaks("log10", function(x) 10^x),
        labels = trans_format("log10", math_format(10^.x))) +
  theme_classic() +
  labs(y = "Screening time (S)", x = "") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.position = "none") +
  theme(axis.line = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(size = 0)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black")) +
  theme(axis.text.x = element_text(size = 0)) +
  theme(axis.text.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 0)) +
ggsave("Screen_time.jpeg", width = 3.5, height = 1.5, path = "/Users/troymcdiarmid/Desktop/")

##Statistical test of effect of peel on screening time for F53B6.7

screen_time_integrant_data_53 <- screen_time_integrant_data %>% 
  filter(Injector_gene %in% c("T_F53B6.7", "V_F53B6.7")) 

res<-wilcox.test(Screening_time ~ Treatment, data=screen_time_integrant_data_53)
res

##Statistical test of effect of peel on screening time for F10E9.2

screen_time_integrant_data_10 <- screen_time_integrant_data %>% 
  filter(Injector_gene %in% c("T_F10E9.2", "T_F10E9.2")) 

res<-wilcox.test(Screening_time ~ Treatment, data=screen_time_integrant_data_10)
res

```

```{r}
##Making a plot of the proportion of plates where integrants were found

##Calculate the proportion of plates where integrants were found

screen_time_data_day1 <- screen_time_data %>% 
  filter(!Screening_day == 2)

integrant_proportion_data <- screen_time_data_day1 %>% 
  group_by(Injector_gene, Treatment) %>% 
  summarise(Integrant_proportion = (mean(Integrant_found)*100))

##Order the factors for plotting

integrant_proportion_data$Injector_gene <- factor(integrant_proportion_data$Injector_gene,
    levels = c('T_F10E9.2', 'V_F10E9.2', 'T_F53B6.7', 'V_F53B6.7'), ordered = TRUE)

##Creating a plot to compare the proportion of plates bearing integrants

##Plot of the data for F53

integrant_proportion_F53 <- integrant_proportion_data %>% 
  filter(Injector_gene %in% c("T_F53B6.7", "V_F53B6.7"))

ggplot(integrant_proportion_F53, aes(fill=Treatment, y=Integrant_proportion, x=Injector_gene)) + geom_bar(position = position_dodge(width = 0.8), stat="identity", width = 0.5, show.legend = FALSE) +
theme_classic() +
  labs(y = "Plates with integrants (%)", x = "") +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,100)) +
  coord_cartesian(clip = "off") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.text= element_text(family="Arial Bold")) +
  theme(axis.line = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(size = 0)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black")) +
  theme(axis.text.x = element_text(size = 0)) +
  theme(axis.text.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 0)) +
  scale_fill_manual(values = c("black", "dodgerblue2")) +
ggsave("F53_integrant_proportion.jpeg", width = 1.5, height = 2.2, path = "/Users/troymcdiarmid/Desktop/")

##Plot of the data for F10

integrant_proportion_F53 <- integrant_proportion_data %>% 
  filter(Injector_gene %in% c("T_F10E9.2", "V_F10E9.2"))

ggplot(integrant_proportion_F53, aes(fill=Treatment, y=Integrant_proportion, x=Injector_gene)) + geom_bar(position = position_dodge(width = 0.8), stat="identity", width = 0.5, show.legend = FALSE) +
theme_classic() +
  labs(y = "Plates with integrants (%)", x = "") +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,100)) +
  coord_cartesian(clip = "off") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.text= element_text(family="Arial Bold")) +
  theme(axis.line = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(size = 0)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black")) +
  theme(axis.text.x = element_text(size = 0)) +
  theme(axis.text.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.y = element_text(family="Arial", colour = "black", size = 8)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 0)) +
  scale_fill_manual(values = c("black", "dodgerblue2")) +
ggsave("F10_integrant_proportion.jpeg", width = 1.5, height = 2.2, path = "/Users/troymcdiarmid/Desktop/")

```

```{r}
##Making a plot of the proportion of starved plates for pbs-1 and K04F10.3 screened 7 and 10 days post-injection

##Plot of day 7 data:

setwd("/Users/troymcdiarmid/Documents/Peel_materials/")

starve_data_pbs_k04 <- read_csv("/Users/troymcdiarmid/Documents/Peel_materials/peel_plate_starve_pbs_K04_7day.csv", col_names = TRUE)

ggplot(starve_data_pbs_k04, aes(fill=Treatment, y=Proportion_starved, x=Gene)) + geom_bar(position = position_dodge(width = 0.7), stat="identity", width = 0.5, show.legend = FALSE) +
theme_classic() +
  labs(y = "Plates with starvation (%)", x = "") +
  scale_y_continuous(position = "right", expand = c(0,0),
                     limits = c(0,75), breaks = c(0,25,50,75)) +
  coord_cartesian(clip = "off") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.text= element_text(family="Arial Bold")) +
  theme(axis.line = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(size = 0)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black")) +
  theme(axis.text.x = element_text(size = 0)) +
  theme(axis.text.y.right = element_text(family="Arial", colour = "black", size = 8, angle = 90, hjust = 0.5)) +
  theme(axis.title.y.right = element_text(family="Arial", colour = "black", size = 8, angle = 90)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 0)) +
  scale_fill_manual(values = c("black", "dodgerblue2")) +
ggsave("plate_starve_pbs_k04.jpeg", width = 1.5, height = 2.8, path = "/Users/troymcdiarmid/Desktop/")

##Plot of day 10 data

setwd("/Users/troymcdiarmid/Documents/Peel_materials/")

starve_data_pbs_k04_10 <- read_csv("/Users/troymcdiarmid/Documents/Peel_materials/peel_plate_starve_pbs_K04_10day.csv", col_names = TRUE)

ggplot(starve_data_pbs_k04_10, aes(fill=Treatment, y=Proportion_starved, x=Gene)) + geom_bar(position = position_dodge(width = 0.7), stat="identity", width = 0.5, show.legend = FALSE) +
theme_classic() +
  labs(y = "Plates with starvation (%)", x = "") +
  scale_y_continuous(position = "right", expand = c(0,0),
                     limits = c(0,75), breaks = c(0,25,50,75)) +
  coord_cartesian(clip = "off") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.text= element_text(family="Arial Bold")) +
  theme(axis.line = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(size = 0)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black")) +
  theme(axis.text.x = element_text(size = 0)) +
  theme(axis.text.y.right = element_text(family="Arial", colour = "black", size = 8, angle = 90, hjust = 0.5)) +
  theme(axis.title.y.right = element_text(family="Arial", colour = "black", size = 8, angle = 90)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 0)) +
  scale_fill_manual(values = c("black", "dodgerblue2")) +
ggsave("plate_starve_pbs_k04_10.jpeg", width = 1.5, height = 2.8, path = "/Users/troymcdiarmid/Desktop/")

```

```{r}
##Making a plot of the effect of multiple heatshock rounds on days 5,7,9 on plate starvation 10 days post-injection

setwd("/Users/troymcdiarmid/Documents/Peel_materials/")

starve_data_pbs_k04_10_579 <- read_csv("/Users/troymcdiarmid/Documents/Peel_materials/peel_plate_starve_pbs_K04_multiday.csv", col_names = TRUE)

## Plot for PBS-1

starve_data_pbs_10_579 <- starve_data_pbs_k04_10_579 %>% 
  filter(Gene %in% c("pbs-1"))

ggplot(starve_data_pbs_10_579, aes(fill=Treatment, y=Proportion_starved, x=Gene_day)) + geom_bar(position = position_dodge(width = 0.7), stat="identity", width = 0.5, show.legend = FALSE) +
theme_classic() +
  labs(y = "Plates with starvation (%)", x = "") +
  scale_y_continuous(position = "right", expand = c(0,0),
                     limits = c(0,75), breaks = c(0,25,50,75)) +
  coord_cartesian(clip = "off") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.text= element_text(family="Arial Bold")) +
  theme(axis.line = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(size = 0)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black")) +
  theme(axis.text.x = element_text(size = 0)) +
  theme(axis.text.y.right = element_text(family="Arial", colour = "black", size = 8, angle = 90, hjust = 0.5)) +
  theme(axis.title.y.right = element_text(family="Arial", colour = "black", size = 8, angle = 90)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 0)) +
  scale_fill_manual(values = c("black", "dodgerblue2")) +
ggsave("plate_starve_pbs_multiday.jpeg", width = 1.5, height = 2.8, path = "/Users/troymcdiarmid/Desktop/")

## Plot for K04F10.3

starve_data_K04_10_579 <- starve_data_pbs_k04_10_579 %>% 
  filter(Gene %in% c("K04F10.3"))

ggplot(starve_data_K04_10_579, aes(fill=Treatment, y=Proportion_starved, x=Gene_day)) + geom_bar(position = position_dodge(width = 0.7), stat="identity", width = 0.5, show.legend = FALSE) +
theme_classic() +
  labs(y = "Plates with starvation (%)", x = "") +
  scale_y_continuous(position = "right", expand = c(0,0),
                     limits = c(0,75), breaks = c(0,25,50,75)) +
  coord_cartesian(clip = "off") +
  theme(legend.title= element_text(family="Arial Bold")) +
  theme(legend.text= element_text(family="Arial Bold")) +
  theme(axis.line = element_line(colour = 'black', size = 0.4)) + 
  theme(axis.line.x = element_line(size = 0)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.4)) +
  theme(axis.ticks.length=unit(.03, "in")) +
  theme(axis.ticks.x = element_line(size = 0)) +
  theme(axis.text = element_text(family="Arial", colour = "black")) +
  theme(axis.text.x = element_text(size = 0)) +
  theme(axis.text.y.right = element_text(family="Arial", colour = "black", size = 8, angle = 90, hjust = 0.5)) +
  theme(axis.title.y.right = element_text(family="Arial", colour = "black", size = 8, angle = 90)) +
  theme(axis.title.x = element_text(family="Arial", colour = "black", size = 0)) +
  scale_fill_manual(values = c("black", "dodgerblue2")) +
ggsave("plate_starve_K04_multiday.jpeg", width = 1.5, height = 2.8, path = "/Users/troymcdiarmid/Desktop/")


```

